In [1]:
# 多元一次方程求解
# 比如求解 y = w1 * x1 + w2 * x2 + ... + w5 * x5 等这样包含5个随机变量的方程

import tensorflow as tf
import numpy as np



In [53]:
train_count = 100 # 提供10 组训练集
w_count = 5 # 5个未知参数
t_x = np.floor(100 * np.random.random([train_count, w_count]), dtype=np.float32)
t_x

array([[ 48.,  11.,  44.,  70.,  15.],
       [ 24.,  62.,  47.,  25.,   1.],
       [ 63.,  71.,  71.,  96.,  39.],
       [ 85.,  62.,  12.,  49.,  21.],
       [ 70.,  14.,  83.,  20.,  75.],
       [ 57.,  59.,   8.,  80.,  75.],
       [  6.,  67.,  40.,  73.,  58.],
       [ 78.,  41.,  91.,  60.,  32.],
       [ 26.,  76.,  45.,  27.,  69.],
       [ 24.,  88.,  84.,  31.,   4.],
       [ 57.,  77.,  40.,  47.,  11.],
       [ 46.,  61.,  98.,  93.,  42.],
       [ 19.,  44.,  63.,  82.,  80.],
       [  8.,  29.,  95.,  71.,  43.],
       [ 39.,  42.,   7.,  32.,  49.],
       [ 22.,  74.,  69.,   9.,  61.],
       [ 17.,  77.,   7.,   8.,  22.],
       [ 63.,  32.,  78.,  18.,  64.],
       [  3.,  52.,  74.,  77.,  49.],
       [ 59.,  15.,  11.,  47.,  66.],
       [ 69.,  59.,  54.,  80.,  14.],
       [ 72.,  26.,  56.,  51.,   5.],
       [  8.,  96.,  84.,  64.,  54.],
       [ 60.,  79.,  63.,  75.,  29.],
       [ 56.,  69.,  34.,   0.,  20.],
       [ 35.,  14.,  60.,

In [54]:
t_w = np.floor(10 * np.random.random([w_count, 1]), dtype=np.float32)
t_y = t_x.dot(t_w) # numpy 的点积
print(t_w)
print(t_y)

[[ 1.]
 [ 2.]
 [ 1.]
 [ 4.]
 [ 8.]]
[[  514.]
 [  303.]
 [  972.]
 [  585.]
 [  861.]
 [ 1103.]
 [  936.]
 [  747.]
 [  883.]
 [  440.]
 [  527.]
 [  974.]
 [ 1138.]
 [  789.]
 [  650.]
 [  763.]
 [  386.]
 [  789.]
 [  881.]
 [  816.]
 [  673.]
 [  424.]
 [  972.]
 [  813.]
 [  388.]
 [  995.]
 [  829.]
 [  493.]
 [  679.]
 [ 1404.]
 [  509.]
 [  716.]
 [ 1032.]
 [  532.]
 [  371.]
 [  775.]
 [  483.]
 [  958.]
 [ 1039.]
 [  759.]
 [  853.]
 [  589.]
 [  351.]
 [  336.]
 [  687.]
 [  488.]
 [ 1100.]
 [ 1153.]
 [ 1161.]
 [ 1017.]
 [  764.]
 [  573.]
 [  602.]
 [ 1206.]
 [ 1058.]
 [  402.]
 [ 1040.]
 [ 1066.]
 [  888.]
 [ 1212.]
 [  821.]
 [  322.]
 [  495.]
 [  699.]
 [  616.]
 [  613.]
 [  736.]
 [ 1066.]
 [  675.]
 [ 1120.]
 [ 1156.]
 [  891.]
 [ 1307.]
 [  893.]
 [  748.]
 [  806.]
 [  639.]
 [  775.]
 [  865.]
 [  147.]
 [  559.]
 [  286.]
 [  703.]
 [  462.]
 [  682.]
 [ 1259.]
 [  323.]
 [  987.]
 [  908.]
 [ 1382.]
 [  849.]
 [  428.]
 [  684.]
 [ 1010.]
 [  510.]
 [  496.]
 [  

In [55]:
# 定义x 和y 变量
x = tf.placeholder(tf.float32, shape=[train_count, w_count])
y = tf.placeholder(tf.float32, shape=[train_count, 1])


In [56]:
#w 是要求的各个参数的权重，是目标输出，对应 t_w
w = tf.Variable(np.zeros(w_count, dtype=np.float32).reshape((w_count, 1)), tf.float32)

In [67]:
# 定义计算结果y 和损失函数，已经训练方法
now_y = tf.matmul(x, w)
loss = tf.reduce_sum(tf.square(now_y - y))
optimizer = tf.train.GradientDescentOptimizer(0.000001)
#optimizer = tf.train.AdadeltaOptimizer(0.001)
train = optimizer.minimize(loss)

In [68]:
# 可以设置一个阈值，损失函数小于特定的值的时候就终止训练
min_loss_value = tf.constant(1e-5)

In [69]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
run_count = 0
last_loss = 0

In [70]:
while True:
    run_count += 1
    sess.run(train, {x:t_x, y:t_y})
    
    curr_loss, is_ok = sess.run([loss, loss < min_loss_value], {x:t_x, y:t_y})
    print("run count %s , loss = %s  " % (run_count, curr_loss))
    
    if last_loss == curr_loss:
        break
        
    last_loss = curr_loss
    
    if is_ok or run_count >= 10000:
        break

run count 1 , loss = 1.63319e+08  
run count 2 , loss = 4.07436e+08  
run count 3 , loss = 1.0228e+09  
run count 4 , loss = 2.57218e+09  
run count 5 , loss = 6.47191e+09  
run count 6 , loss = 1.62865e+10  
run count 7 , loss = 4.09865e+10  
run count 8 , loss = 1.03148e+11  
run count 9 , loss = 2.59585e+11  
run count 10 , loss = 6.5328e+11  
run count 11 , loss = 1.64407e+12  
run count 12 , loss = 4.13752e+12  
run count 13 , loss = 1.04126e+13  
run count 14 , loss = 2.62048e+13  
run count 15 , loss = 6.59479e+13  
run count 16 , loss = 1.65967e+14  
run count 17 , loss = 4.17678e+14  
run count 18 , loss = 1.05114e+15  
run count 19 , loss = 2.64535e+15  
run count 20 , loss = 6.65737e+15  
run count 21 , loss = 1.67542e+16  
run count 22 , loss = 4.21642e+16  
run count 23 , loss = 1.06112e+17  
run count 24 , loss = 2.67045e+17  
run count 25 , loss = 6.72055e+17  
run count 26 , loss = 1.69132e+18  
run count 27 , loss = 4.25643e+18  
run count 28 , loss = 1.07119e+19  
run

In [72]:
curr_w, curr_loss = sess.run([w, loss], {x:t_x, y:t_y})
print(curr_w )
print(curr_loss)

[[ -1.26550889e+16]
 [ -1.39529174e+16]
 [ -1.38445941e+16]
 [ -1.43327150e+16]
 [ -1.25873122e+16]]
inf
